// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: proto/munitions.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MunitionsServiceClient is the client API for MunitionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MunitionsServiceClient interface {
	// SolicitarM es el método para pedir municiones.
	SolicitarM(ctx context.Context, in *SolicitarMRequest, opts ...grpc.CallOption) (*SolicitarMResponse, error)
}

type munitionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMunitionsServiceClient(cc grpc.ClientConnInterface) MunitionsServiceClient {
	return &munitionsServiceClient{cc}
}

func (c *munitionsServiceClient) SolicitarM(ctx context.Context, in *SolicitarMRequest, opts ...grpc.CallOption) (*SolicitarMResponse, error) {
	out := new(SolicitarMResponse)
	err := c.cc.Invoke(ctx, "/grpc.MunitionsService/SolicitarM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MunitionsServiceServer is the server API for MunitionsService service.
// All implementations must embed UnimplementedMunitionsServiceServer
// for forward compatibility
type MunitionsServiceServer interface {
	// SolicitarM es el método para pedir municiones.
	SolicitarM(context.Context, *SolicitarMRequest) (*SolicitarMResponse, error)
	mustEmbedUnimplementedMunitionsServiceServer()
}

// UnimplementedMunitionsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMunitionsServiceServer struct {
}

func (UnimplementedMunitionsServiceServer) SolicitarM(context.Context, *SolicitarMRequest) (*SolicitarMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolicitarM not implemented")
}
func (UnimplementedMunitionsServiceServer) mustEmbedUnimplementedMunitionsServiceServer() {}

// UnsafeMunitionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MunitionsServiceServer will
// result in compilation errors.
type UnsafeMunitionsServiceServer interface {
	mustEmbedUnimplementedMunitionsServiceServer()
}

func RegisterMunitionsServiceServer(s grpc.ServiceRegistrar, srv MunitionsServiceServer) {
	s.RegisterService(&MunitionsService_ServiceDesc, srv)
}

func _MunitionsService_SolicitarM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolicitarMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MunitionsServiceServer).SolicitarM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.MunitionsService/SolicitarM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MunitionsServiceServer).SolicitarM(ctx, req.(*SolicitarMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MunitionsService_ServiceDesc is the grpc.ServiceDesc for MunitionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MunitionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.MunitionsService",
	HandlerType: (*MunitionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SolicitarM",
			Handler:    _MunitionsService_SolicitarM_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/munitions.proto",
}
